// Worker entrypoint (wrangler.jsonc `main`). Wraps OpenNext's generated worker.
//
// Why it exists: on Workers Free each request gets 10 ms CPU, and merely
// entering OpenNext/Next costs more than that (Error 1102 on reload). So:
//   - cacheable GETs (pages, robots/sitemap/OG images, /api/stats) are answered
//     from caches.default, keyed by the deploy's version id, WITHOUT importing
//     OpenNext;
//   - /api/geo is answered directly from request.cf;
//   - prerendered pages (HTML, RSC navigation payloads, segment prefetches) are
//     served from the build output via env.ASSETS (scripts/emit-prerender-assets.mjs),
//     so they never render at request time and never miss a cache;
//   - everything else (and every cache miss) dynamically imports OpenNext.
// Rules live in src/lib/edge-cache.ts (pure, unit-tested).
// OpenNext must never be imported at top level here: the import is the cost.
import { cacheRule, clientCacheControl, geoBody, isStorable, prerenderRule } from "./src/lib/edge-cache.ts";
// Generated by `pnpm build:cf` (emit-prerender-assets.mjs); bundled by wrangler.
import prerender from "./.open-next/prerender-routes.json";
// /api/visit and /api/poll run here directly (D1 binding), not through Next:
// entering OpenNext cost them 186-237 ms CPU on a 10 ms plan.
import { handlePoll, handleVisit } from "./src/lib/visitor-handlers.ts";

function visitorDeps(request, env) {
  return {
    db: env.DB,
    env: { VISITOR_SALT: env.VISITOR_SALT, NODE_ENV: "production" },
    now: () => Date.now(),
    geo: geoBody(request.cf),
  };
}

let openNext = null;
async function next(request, env, ctx) {
  openNext ??= (await import("./.open-next/worker.js")).default;
  return openNext.fetch(request, env, ctx);
}

function withHeaders(res, headers, head) {
  const out = new Response(head ? null : res.body, res);
  for (const [k, v] of Object.entries(headers)) out.headers.set(k, v);
  return out;
}

const worker = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname === "/api/geo" && request.method === "GET") {
      return Response.json(geoBody(request.cf), { headers: { "cache-control": "no-store", "x-edge-cache": "DIRECT" } });
    }

    if (url.pathname === "/api/visit" && request.method === "POST") return handleVisit(request, visitorDeps(request, env));
    if (url.pathname === "/api/poll" && (request.method === "GET" || request.method === "POST")) {
      return handlePoll(request, visitorDeps(request, env));
    }

    const pre = prerenderRule(request, prerender);
    if (pre) {
      const head = request.method === "HEAD";
      if (pre.kind === "segment-miss") return new Response(null, { status: 204, headers: pre.headers });
      const asset = await env.ASSETS.fetch(new Request(new URL(pre.asset, url.origin), { method: "GET" }));
      if (asset.status === 200) return new Response(head ? null : asset.body, { status: 200, headers: pre.headers });
      // Missing asset (should not happen): fall through to the cache/Next path below.
    }

    const version = env.CF_VERSION_METADATA?.id ?? "dev";
    const rule = cacheRule(request, version, typeof request.cf?.country === "string" ? request.cf.country : null);
    if (rule.kind === "bypass") return next(request, env, ctx);

    const head = request.method === "HEAD";
    const cache = caches.default;
    const key = new Request(rule.key, { method: "GET" });
    const hit = await cache.match(key);
    if (hit) return withHeaders(hit, { "cache-control": clientCacheControl(rule.kind), "x-edge-cache": "HIT" }, head);

    // Miss: render through Next with a GET (so HEAD can fill the cache too).
    const res = await next(head ? new Request(request, { method: "GET" }) : request, env, ctx);
    if (!isStorable(res)) return withHeaders(res, { "x-edge-cache": "BYPASS" }, head);
    const stored = withHeaders(res.clone(), { "cache-control": `public, max-age=${rule.ttl}` }, false);
    stored.headers.delete("x-edge-cache");
    ctx.waitUntil(cache.put(key, stored).catch(() => {}));
    return withHeaders(res, { "cache-control": clientCacheControl(rule.kind), "x-edge-cache": "MISS" }, head);
  },
};

export default worker;
