import { createRequire } from "module";
const require = createRequire("/Users/knamnguyen/Documents/0-Programming/duma/package.json");
const { chromium } = require("playwright");
import fs from "fs";
const OUT = "/Users/knamnguyen/Documents/0-Programming/portfolio-2026/process/features/portfolio-site/active/autoresearch-ux-261004_04-10-26/research/R2-shots/motion";
const browser = await chromium.launch();
const page = await (await browser.newContext({viewport:{width:1440,height:900}})).newPage();
await page.goto("http://localhost:3003/",{waitUntil:"load"}); await page.waitForTimeout(1500);
await page.evaluate(()=>{const c=document.querySelectorAll("[data-testid=stack-card]")[2]; window.scrollTo(0, window.scrollY + c.getBoundingClientRect().top - innerHeight*1.05)}); await page.waitForTimeout(600);
const before = await page.evaluate(()=>document.querySelectorAll("[data-testid=card-stamp]")[2].dataset.landed);
const sp = page.evaluate(()=>new Promise(r=>{const s=document.querySelectorAll("[data-testid=card-stamp]")[2]; const inner=s.firstElementChild; const card=document.querySelectorAll("[data-testid=stack-card]")[2]; const out=[]; const t0=performance.now();
 (function f(){const t=performance.now()-t0; const cs=getComputedStyle(inner); const m=cs.transform.match(/matrix\(([^)]+)\)/); let sc=null,rot=null; if(m){const [a,b]=m[1].split(",").map(Number); sc=+Math.hypot(a,b).toFixed(3); rot=+(Math.atan2(b,a)*180/Math.PI).toFixed(1)} const halo=inner.querySelector("span"); const bs=halo?getComputedStyle(halo).boxShadow:""; const sp=bs.match(/(\d+)px (\d+)px (\d+)px (\d+)px$/); out.push([Math.round(t),sc,rot,+(+cs.opacity).toFixed(2),s.dataset.landed,bs.slice(0,22),+card.getBoundingClientRect().top.toFixed(1)]); if(t<1500) requestAnimationFrame(f); else r(out)})();}));
await page.waitForTimeout(100);
await page.evaluate(()=>{const c=document.querySelectorAll("[data-testid=stack-card]")[2]; window.scrollTo(0, window.scrollY + c.getBoundingClientRect().top - innerHeight*0.55)});
const d = await sp;
const li = d.findIndex(x=>x[4]==="true");
console.log("before",before,"landed at idx",li, d[li]?.[0]);
for (const x of d.slice(Math.max(0,li-1), li+40).filter((_,i)=>i%2===0)) console.log(x.join(" | "));
const cardTops = d.slice(li).map(x=>x[6]); console.log("card top range after land", Math.min(...cardTops), Math.max(...cardTops), "start", cardTops[0]);
await browser.close();
