#!/usr/bin/env python3
"""Regenerate src/lib/seo/og-assets.ts: the B&W portrait (flattened onto the OG
panel colour, as JPEG — Satori cannot read WebP) and the Twemoji SVGs for the
project emoji, embedded as data URIs so OG rendering never fetches anything.
Run: python3 scripts/gen-og-assets.py  (needs Pillow; network for Twemoji)."""
import base64, io, os, urllib.request
from PIL import Image

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PANEL = (240, 240, 243)

im = Image.open(os.path.join(root, "public/portrait/thao-bw.webp")).convert("RGBA")
w = 520; h = round(im.height * w / im.width)
im = im.resize((w, h), Image.LANCZOS)
bg = Image.new("RGB", im.size, PANEL); bg.paste(im, mask=im.split()[3])
buf = io.BytesIO(); bg.save(buf, "JPEG", quality=84, optimize=True)
portrait = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

EMOJI = {"🧾": "1f9fe", "🔎": "1f50e", "🛡️": "1f6e1", "💸": "1f4b8", "🪙": "1fa99",
         "☁️": "2601", "🔗": "1f517", "📒": "1f4d2", "🎮": "1f3ae", "👩‍💻": "1f469-200d-1f4bb"}
lines = ["// GENERATED by scripts/gen-og-assets.py — do not edit by hand.",
         f'export const PORTRAIT_SIZE = {{ width: {w}, height: {h} }} as const;',
         f'export const PORTRAIT_DATA_URI = "{portrait}";',
         "export const PORTRAIT_PANEL = \"#%02x%02x%02x\";" % PANEL,
         "/** Twemoji (CC-BY 4.0, https://github.com/jdecked/twemoji) as data URIs, keyed by emoji. */",
         "export const EMOJI_DATA_URI: Record<string, string> = {"]
for ch, cp in EMOJI.items():
    svg = urllib.request.urlopen(f"https://cdn.jsdelivr.net/gh/jdecked/twemoji@latest/assets/svg/{cp}.svg").read()
    lines.append(f'  {ch!r}: "data:image/svg+xml;base64,{base64.b64encode(svg).decode()}",'.replace("'", '"', 2))
lines.append("};")
open(os.path.join(root, "src/lib/seo/og-assets.ts"), "w").write("\n".join(lines) + "\n")
print(len(portrait))
