#!/usr/bin/env python3
"""Regenerate src/lib/seo/og-fonts.ts: static, subset TTFs (Satori cannot read
woff2 or variable fonts) taken from the self-hosted @fontsource packages and
embedded as base64, so the OG image routes need no fs/fetch on Workers.
Run: python3 scripts/gen-og-fonts.py   (needs fonttools + brotli)"""
import base64, io, os
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
nm = os.path.join(root, "node_modules")
TEXT = "".join(chr(c) for c in range(0x20, 0x7F)) + "·—–…’‘“”•→↗©é"

def build(path, axes):
    f = TTFont(path)
    f = instancer.instantiateVariableFont(f, axes)
    opts = subset.Options(); opts.layout_features = ["kern", "liga"]; opts.name_IDs = [1, 2]
    s = subset.Subsetter(opts); s.populate(text=TEXT); s.subset(f)
    f.flavor = None
    buf = io.BytesIO(); f.save(buf)
    return base64.b64encode(buf.getvalue()).decode()

arch = os.path.join(nm, "@fontsource-variable/archivo/files/archivo-latin-wdth-normal.woff2")
inter = os.path.join(nm, "@fontsource-variable/inter/files/inter-latin-wght-normal.woff2")
out = {
  "ARCHIVO_700_B64": build(arch, {"wght": 700, "wdth": 118}),
  "INTER_400_B64": build(inter, {"wght": 400}),
  "INTER_600_B64": build(inter, {"wght": 600}),
}
lines = ["// GENERATED by scripts/gen-og-fonts.py — do not edit by hand.",
         "// Static subset TTFs (Archivo 700 @ width 118, Inter 400/600) for next/og."]
for k, v in out.items():
    lines.append(f'export const {k} = "{v}";')
open(os.path.join(root, "src/lib/seo/og-fonts.ts"), "w").write("\n".join(lines) + "\n")
print({k: len(v) for k, v in out.items()})
